version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"

  web:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - .:/app  # Mount the current directory to /app in the container